### PR TITLE
Clean some code and add option to get the image dimensions

### PR DESCRIPTION
**Pull request by spoit**

### CODE REVIEW

**Comment by frizinak** [comment]
disgusting, honestly

getJson for get_width AND get_height

this should be done without an http call OR a cron queue not in friggin twig,

render a gallery with 30 images = 60 api calls for calculatable data.

If imgix is fast, let's say 50ms, you've just added 3 seconds. Only depending on anonymous page cache. (This is assuming imgix already has the image, which we all know expires every N hours for rarely requested assets)

Using imgix and forgiving its slow as f* client side async rendering is one thing, adding it to the page load is plain ridiculous.

**Comment by spoit** [comment]
Easy, I know, I know,

Since the feature was requested by frontend but then was deemed unnecessary after all by same frontend I wrapped it up as quickly as possible and left it at that.

1. It's not enforced so you don't have to use it

2. True: One could keep the JSON data in the instance so the API call only happens once instead of twice

3. Also true: the JSON data could be fetched on upload/cron but then you have to do this for every preset (which is 15 calls per image) and keep it somewhere (cache? state? extra db field in the fieldType table?)

4. More true: Eventually in normal Drupal installations render cache will cache this so the call only happens (twice) for each image (if you're using it, I would not advice with every image) with an empty cache

I agree there is a lot to improve and it is quite unusable in production envs but I'm not going to work further on this when no one will use it. Just throw it away then?

**Comment by frizinak** [comment]
15 calls per image at the cron queue's leisure is still better than adding it to page load...

'in normal drupal installations' well as long as they don't use the default hook_theme, don't use #lazy_loader or all users are anonymous, well then yes.

throw it away, frontenders are not aware of what happens in the background, they WILL use it.

and let's keep branch names useful or make changes from personal forks. feature/updates as opposed to feature/downgrades?

**Comment by spoit** [comment]
Problem solved :)

**Pull request closed without merging**
